[package]
name = "ifpfs-uploader"
version = "0.1.0"
edition = "2018"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[dependencies]
log = "0.4"
env_logger = "0.9"
structopt = "0.3"

[[bin]]
name = "ipfs-uploader"